server:
  port: 9090
#datasource properties
spring:
  datasource:
     url : jdbc:mysql://localhost:3306/jrtp
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
     dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
plans-api:
     messages:
         plansavesuccess: "Plan Saved Sucessfully"
         plansavefailed: "Plan Saved Failed"
         planupdatesuccess: "Plan Updated Successfully"
         planupdatefailed: "Plan Update Failed"
         plandeletesuccess: "Plan Deleted Successfully"
         plandeletefailed: "Plan Delete Failed"
         planstatussuccess: "Plan status Updated Successfully"
         planstatusfailed: "Plan status not Updated"
